<div class="right-column fl">
    <div class="map-container">
        <div class="border">
            <div id="map"></div>
        </div>
    <script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -34.397, lng: 150.644},
          zoom: 8
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhi9yR0zX6_t8go1AWUQnmbytgpiqYhgY&callback=initMap"
    async defer></script>
    </div>
</div>
